### ISSUE TITLE
provide example of executing with browserstack

### ISSUE THREAD

**Issue by abhinaba-ghosh** [abhinaba-ghosh/testcafe-lighthouse#5]

**Comment by ayemelyanenko-chegg** [comment]
Hi again @abhinaba-ghosh, is there an example that can be used to get this running with browserstack? Thanks

**Comment by abhinaba-ghosh** [comment]
hi I am working on the same. You will get an update by this weekend.

**Comment by ayemelyanenko-chegg** [comment]
Thank you

**Comment by abhinaba-ghosh** [comment]
Hi @ayemelyanenko-chegg, I do have a request for you. If you already having browserstack account, can you check https://www.browserstack.com/automate/testcafe and follow the execution guideline. Let me know if any specific error you encounter for this library. Let me know if this can be done from your side.

**Comment by ayemelyanenko-chegg** [comment]
Hi @abhinaba-ghosh I wonder what would be the command line runner. In order to run this library, I need to provide the port.

For example, for browserstack, I can run a regular sample test like this: 
testcafe "browserstack:Chrome@53.0:Windows 10" "test.js"

With this library, I need to put the port somewhere (cdpPort=9222) and also browserstack uses real browsers and not emulators. 

Do you know where the port needs to go in the sample command for browserstack above?

**Comment by abhinaba-ghosh** [comment]
@miherlosev can you provide some guidance here?

**Comment by abhinaba-ghosh** [comment]
@ayemelyanenko-chegg , please upvote this issue: https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/124

**Comment by abhinaba-ghosh** [comment]
as per the comment in https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/124

"BrowserStack doesn't provide an API to work with the DevTools protocol. Therefore, at this moment there is no way to achieve this functionality."
